### ISSUE TITLE
TypeScript typings

### ISSUE THREAD

**Issue by lirbank** [nlpcloud/nlpcloud-js#1]
It would be awesome if you could include typings for TypeScript either as part of this package (preferably) or alternatively as a [DT](https://github.com/DefinitelyTyped/DefinitelyTyped).

Thanks for providing an awesome NLP service!

**Comment by juliensalinas** [comment]
Hi @lirbank thanks for the suggestion, we will have a look ASAP, this is a good idea indeed.
(and thanks for the warm message ;) )

**Comment by juliensalinas** [comment]
Hi @lirbank would you mind having a look at the PR and let me know if this is what you expected?
--> https://github.com/nlpcloud/nlpcloud-js/pull/2

I simply used Typescript to automatically generate types from the existing `.js` file (https://www.typescriptlang.org/docs/handbook/declaration-files/dts-from-js.html). I did not set the types by myself.

If you think that something is missing please don't hesitate to comment!

Thanks.

**Comment by lirbank** [comment]
Cool, thanks! I commented in the PR https://github.com/nlpcloud/nlpcloud-js/pull/2#issuecomment-941227230
