### ISSUE TITLE
Possibility to train a custom model

### ISSUE THREAD

**Issue by staminna** [nlpcloud/nlpcloud-js#11]
Dear nlpcloud,

Is there the possibility to train a custom model, providing the necessary computation power required?

**Comment by juliensalinas** [comment]
Hello @staminna, thanks for your message,
Unfortunately this is not possible. However it is possible for you to train your own model and then upload it to NLP Cloud for production deployment.
Please don't hesitate to ask me more questions!

**Comment by staminna** [comment]
I have a 1.6GB JSON file I would like NLP Cloud to learn from, so that should be possible, right?

**Comment by juliensalinas** [comment]
Yes  absolutely, you can train GPT-J on NLP Cloud from your 1.6 GB file.
Maybe you will want to convert it to the right format: https://docs.nlpcloud.com/#gpt-j-dataset-format
Maybe we can continue this discussion with our support team? --> support@nlpcloud.com
Looking forward to hearing from you!
