### ISSUE TITLE
Not a problem, but a suggestion

### ISSUE THREAD

**Issue by inf3rnus** [nlpcloud/nlpcloud-js#12]
Hey, just wanted to provide some feedback.

It'd be really convenient if you were to put in an enum of sorts that contained every model that's available by request type.

Would save a trip to the website and help cleanup user code.

**Comment by inf3rnus** [comment]
Second piece of feedback. 

To simplify the params that are passed into any of the methods on the class, you should have the method (e.g. summarization), accept a single object with each of its properties being a required or optional field. 

Would make it a lot easier to look at in user code from a self-documenting perspective.

Just found myself needing to go back to the docs to do some simple maintenance.

Hope that's helpful!

-Aaron

**Comment by juliensalinas** [comment]
Hello @inf3rnus , thanks so much for these suggestions.
We actually totally agree with that. Our Nodejs lib needs some refactoring. Methods with a large number of parameters like text generation should definitely use an object instead...
This is on our roadmap, so we hope we'll start working on this soon!

Thanks again.

**Comment by inf3rnus** [comment]
Well thanks for the reply!

Sounds good, looking forward to whatever you guys end up cooking up 😄

**Comment by juliensalinas** [comment]
This is now implemented in the last major version (v2)!

**Comment by inf3rnus** [comment]
Woot! Excellent work
