### ISSUE TITLE
Use new major version when introducing breaking changes

### ISSUE THREAD

**Issue by n1k0sv** [nlpcloud/nlpcloud-js#13]
Your latest release `1.0.49` introduced a functional change in the way the parameters are passed into the NLPCloudClient interface, and was released as a patch version update. 

This broke our integration with NLPCloud, and loss of trust in the service, trying to figure out what is happening.

I would suggest you do the following:
- Whenever you add breaking changes in the public interface of this library, add a major library update so that people can upgrade your library with confidence.
- Use minor when adding new functionality and patch when fixing bugs.
- Maintain a proper changelog in this repo, or document significant changes like this in your Github releases.

**Comment by juliensalinas** [comment]
Hello @nbasili , thank you so much for this feedback.
You are absolutely right and we are sorry for poorly handling this version bumping.

We just did the following:

- Create a major version (v2.0.0)
- Document the reason for the new version in the Github release
- Delete the v1.0.49 release from Github
- Deprecate the v1.0.49 version from NPM

Sorry again and thank you for your suggestions. Please don't hesitate to comment further if needed, it will be very much appreciated.

Julien

**Comment by n1k0sv** [comment]
Awesome, thank you 🙏
