### ISSUE TITLE
TS definition for return type of embeddings() seems to be wrong?

### ISSUE THREAD

**Issue by ocbreulmann** [nlpcloud/nlpcloud-js#15]
We get this data back from the embeddings() method: 

`response.data = {"embedding": [....]}`

instead of the TS definition: 

`response.data = {"score": [.....]}`

**Comment by juliensalinas** [comment]
Hello @ocbreulmann , thank you for raising this issue, and sorry about this.
We just pushed a fix!
If the problem keeps happening on your end please don't hesitate to reopen this issue.
Thanks again.
