### ISSUE TITLE
feature: discover and utilize account limits

### ISSUE THREAD

**Issue by tomdavidson** [nlpcloud/nlpcloud-js#3]
I think it would be slick if the the client could discover the account limits, such as rate limits the token is approved for and to configure Axios to use that limit. 

This just a nice to have in being  "good" consumers without implementing 429 handling.

**Comment by juliensalinas** [comment]
Thanks @tomdavidson , I totally agree. Our clients are only doing the strict minimum for the moment, but we'll improve that!
