### ISSUE TITLE
chatbot method still missing `context` parameter

### ISSUE THREAD

**Issue by jrglg** [nlpcloud/nlpcloud-js#5]
Context argument is still missing even after update to 1.0.24.

Thank you

**Comment by jrglg** [comment]
![image](https://user-images.githubusercontent.com/52841892/178523659-939224f4-333c-47e7-bb64-5ee5eb4333db.png)

**Comment by juliensalinas** [comment]
Hello @jrglg thanks for your message!
Can you please try the 1.0.25 version? Theoretically it should contain the proper types.
Let me know if it's not the case!

**Comment by juliensalinas** [comment]
Closing as inactive
