### ISSUE TITLE
Translation source and target

### ISSUE THREAD

**Issue by pv-hassam-ullah** [nlpcloud/nlpcloud-js#7]
the translation function does not allow me to specify source and target languages of the text, it only takes the text as a parameter despite the examples in the endpoints documentation showing '**text' , 'source' ,  'target'** as the three parameters of this function.
**Am I missing something here?**

[https://docs.nlpcloud.com/?javascript#translation](url)

Note: I got this probelm while using the nlpcloud package in my NestJs application

**Comment by juliensalinas** [comment]
Hello @pv-hassam-ullah thanks, you're absolutely right, it seems that we forgot to include the "source" and "target" parameters as Typescript types.
We just fixed it. Could you please download the latest version and try again?
Looking forward to hearing from you.

**Comment by pv-hassam-ullah** [comment]
Hello Julien! Yes it's working just fine now.

Additionally I wanted to ask if there is any way that I could generate text outputs based on a specific tone e.g. aggressive, polite etc. I'm using nlpcloud to generate articles and if I could specify the tone of the output that could be of great help.

**Comment by juliensalinas** [comment]
Yes absolutely! What you will need to do here is create a discussion history with a specific tone
For example if you want your AI to be aggressive, you should create a discussion history where the AI is aggressive.
Please don't hesitate to contact our support (support@nlpcloud.com) if it's not working as expected!
