### ISSUE TITLE
Mistake in typescript package

### ISSUE THREAD

**Issue by pv-hassam-ullah** [nlpcloud/nlpcloud-js#8]
the generation endpoint is expecting

- temperature : float,
- length_penalty : float,
- repetition_penalty : float,
- top_p : float,

but in the typescript package, the generation constructor has these values defined as type 'number' which is causing a 422 error from the server

**the constructor also does not have top_p as a parameter at all**

**Comment by juliensalinas** [comment]
Hello @pv-hassam-ullah, thanks for your message,

This is strange, I can't confirm that the top_p parameter is missing. Here it is: https://github.com/nlpcloud/nlpcloud-js/blob/b9bbde34a92404f0a5a283f4de7215f8e47481a7/index.js#L118
Are you maybe using an outdated version of this library?

Also, as far as I know, there is no such thing as `float` in Typescript: https://www.typescriptlang.org/docs/handbook/2/everyday-types.html
Correct me if I'm wrong.

This does not explain why you're getting a 422 error though...
Can you maybe share your request so I can have a look?

Thanks!

**Comment by pv-hassam-ullah** [comment]
My apologies on my ignorance about the typescript types and about the top_p
parameter being present.

const output = this.gptjClient.generation(
jsonData.text,
+jsonData.minLength,
+jsonData.maxLength,
true, //lengthNoInput
'', //endSequence
false, //removeInput
true, //do_sample
1, //num_beams
false, //early_stopping
0, //no_repeat_ngram_size
+jsonData.variants, //num_return_sequences
50, //top_k
1, //top_p
80, //temperature
1, //repetition_penalty
1, //length_penalty
[], //bad_words
false //remove_end_sequence
) [image: image.png]
I have also console logged the input that i am getting from the frontend
before it is sent to the generation function and you can see that i am
getting the values in correct format from the frontend....i dont know why
this is causing a problem [image: image.png]

**Comment by juliensalinas** [comment]
@pv-hassam-ullah I cannot see your image.
Can we continue this discussion on the NLP Cloud support (support@nlpcloud.com)? It will be easier!
Thanks, Looking forward to hearing from you.

Best,

Julien

**Comment by juliensalinas** [comment]
Close as inactive
